### ISSUE TITLE
Decrease output voltage for HSTNS-PL11

### ISSUE THREAD

**Issue by gotofbi** [darwinbeing/HPServerPSUHack#1]
Hi,

If I want to decrease voltage to 10.2v, how can I achieve this?
When I used the calculator, it showed negative resistor which doesn't make sense ;)

**Comment by darwinbeing** [comment]
[[WolframAlpha Solver Output 10.2V](https://www.wolframalpha.com/input?i=R_11%2F%28R_11%2B39.2%2B10%2B4420%29*V_1%3D0.58%2CR_11%3D220*R_1%2F%28R_1%2B220%29%2C1%2F%281%2B3.92%29*12.32%3DR_12%2F%28R_12%2B3.92%29*V_1%2CR_12%3DR_2*1%2F%281%2BR_2%29%2CV_1%3D15.2)](https://www.wolframalpha.com/input?i=%28R_11%2BR_5%29%2F%28R_11%2BR_5%2B39.2%2B10%2B4420%29*V_1%3D2.5%2CR_11%3D1100*R_3%2F%28R_3%2B1100%29%2C1.74%2F%281.74%2B5.11%29*12.29%3DR_12%2F%28R_12%2B5.11%29*V_1%2CR_12%3DR_4*1.74%2F%281.74%2BR_4%29%2CR_5%3D40%2CV_1%3D10.2)
The approach of using resistors in parallel is only effective for increasing output voltage; it cannot be employed to decrease the output voltage. To achieve a reduction in the output voltage, resistor substitution is necessary. Based on the given formula:
R_11=1411 R_12=2.53
For obtaining an output voltage of 10.2V, the utilization of parallel resistors is no longer viable. Instead, it is required to substitute resistor R_123 with a 411-ohm resistor, and simultaneously replace resistor R102 with a 2.53 k-ohm resistor.
