### ISSUE TITLE
HSTNS-PL42 OVP Firmware

### ISSUE THREAD

**Issue by klippard** [darwinbeing/HPServerPSUHack#10]
I have applied the firmware patch to an HSTNS-PL42 supply, and it does not seem to have any affect at all on the OVP protection.

**Comment by darwinbeing** [comment]
Could you upload the original firmware here?

**Comment by klippard** [comment]
[HSTNS-PL42 factory.zip](https://github.com/user-attachments/files/17100059/HSTNS-PL42.factory.zip)

**Comment by klippard** [comment]
I even tried applying the original PL42 firmware you have posted here, then re-applied the patch.  OVP is still kicking in at around 13V.

**Comment by klippard** [comment]
My apologies.  It's working after putting a legitimate voltmeter on it.  The breakout board I was using on the PSU wasn't showing the voltage increase for whatever reason.
