### ISSUE TITLE
PL30 OVP & Pico Display 

### ISSUE THREAD

**Issue by WiredWonder** [darwinbeing/HPServerPSUHack#12]
Hi there,

Thank you for publishing your work! I have two questions if that's OK:

1. The Pico display seems to show the wrong voltage; using the pre-built firmware my output voltage before mods is 12.2v however the display shows 14.4v and 3A that do not change with low load. The watts shows 20W with no load but correctly goes up with small and large loads. Amps goes up with large loads >3A, but volts does not reflect measured volts.
2. What cable is required to do the OVP mod? I have some old PIC ISCP cables but not sure it will work.

My PSU is PL30 Rev 17.

Thanks!

**Comment by darwinbeing** [comment]
You need to change the Gain in the code to 1 and recompile.
https://github.com/darwinbeing/zpsu_mon/blob/cfa0d3d58f343451c08e334653a570b61b1143b9/src/psu_ctrl.c#L219

**Comment by darwinbeing** [comment]
[zephyr_pico_display_pack.uf2.zip](https://github.com/user-attachments/files/17969608/zephyr_pico_display_pack.uf2.zip)
[zephyr_pico_display_pack2.uf2.zip](https://github.com/user-attachments/files/17969609/zephyr_pico_display_pack2.uf2.zip)

**Comment by darwinbeing** [comment]
[In-Circuit Serial Programming (ICSP) Guide](https://ww1.microchip.com/downloads/en/DeviceDoc/30277d.pdf)
