### ISSUE TITLE
PD30

### ISSUE THREAD

**Issue by pulp187** [darwinbeing/HPServerPSUHack#2]
Hi, 

do you have a patch for PD30?  I noticed you have the original PD30 firmware. Did you use the same location to download the firmware? PD30 has only an empty space for the connector on the PCB.  Thanks for sharing all of the info.

![PD30_01](https://github.com/darwinbeing/HPServerPSUHack/assets/132123734/5e523eaf-80a5-4deb-a161-e15cf03b9527)

**Comment by darwinbeing** [comment]
### In-Circuit Serial Programming and Debugging Pinout

Pin1 - GND  
Pin2 - $\overline{\textrm{MCLR}}$  
Pin3 - PGED  
Pin4 - PGEC  
Pin5 - Vcc(3.3V)
