### ISSUE TITLE
PL30

### ISSUE THREAD

**Issue by xrayos** [darwinbeing/HPServerPSUHack#3]
do you have a high resolution image of the soldering points for the resistor to increase the voltage? also, which resistor did you use in your final product that you use for coding the bmw. I'm trying to do the same thing. thanks!

**Comment by darwinbeing** [comment]
### HERE IS MY PL30 OUTPUT 14.4V FOR BMW CODING SETUP
OUTPUT: 1.27K(TO GROUND)
OVP: 4.7K(TO GROUND)
![PL30](https://github.com/darwinbeing/HPServerPSUHack/assets/366633/c6172b04-197e-4d0e-9d53-477e6357c535)

**Comment by xrayos** [comment]
thank you! I'm going to try and patch firmware for OVP

Which are you using for ground to change the output to 14.4v?

![IMG_6943](https://github.com/darwinbeing/HPServerPSUHack/assets/25410810/7dff1594-efb8-4f03-bd99-5300d8f78d03)

**Comment by darwinbeing** [comment]
Same as the markings in the diagram you provided.

**Comment by xrayos** [comment]
Thanks!

what about the 2 potentiometers at the top of the board? can they be use to change the voltage?

**Comment by darwinbeing** [comment]
Using a potentiometer would make it more convenient to adjust the output.

**Comment by xrayos** [comment]
what about these two by the arrows? Can they be used to adjust the voltage? Thanks!


![IMG_6943](https://github.com/darwinbeing/HPServerPSUHack/assets/25410810/4e3fb9c4-3beb-49dc-8b4f-d77a202111e3)

**Comment by darwinbeing** [comment]
No, they cannot.

**Comment by cotfas** [comment]
I am also interested about those two adjustable resistors (potentiometers) at the top.

I have the PL30 and I want to know what are those two pots for?

I think my SMPS is current limited, as I can't draw more than 15amps from it? (I think).
