### ISSUE TITLE
PICO watt meter firmware

### ISSUE THREAD

**Issue by NobodyYouKnow** [darwinbeing/HPServerPSUHack#4]
My Google-Fu is failing me on this one. What is the provenance of the firmware for the PICO wattmeter used in this repository? I am looking for the source code to learn from and tweak. Thanks!

**Comment by darwinbeing** [comment]
[Raspberry Pi Pico Watt Meter Source](https://github.com/darwinbeing/zpsu_mon)

**Comment by NobodyYouKnow** [comment]
Thank you!
