### ISSUE TITLE
HP HSTNS-PD18

### ISSUE THREAD

**Issue by flywire** [darwinbeing/HPServerPSUHack#5]
Does this adapt to the HP HSTNS-PD18 (DPS-750RB A) for 14.4V?

![image](https://github.com/darwinbeing/HPServerPSUHack/assets/11288701/9d2a2f72-318c-4f09-bb4a-445dc55af0b9)

![image](https://github.com/darwinbeing/HPServerPSUHack/assets/11288701/7ca52459-0837-47a7-b083-fdf0db694002)

 It has a different daughterboard.

![image](https://github.com/darwinbeing/HPServerPSUHack/assets/11288701/a61c4266-e75b-4d32-9143-b497da6acc47)

**Comment by ra1nb0w** [comment]
Do you know if the i2c is also usable on this PSU? thanks

**Comment by darwinbeing** [comment]
@ra1nb0w 
I don't have access to this power supply, so I can't confirm if it supports accessing electrical parameters via I2C. It's highly possible that this power supply doesn't support it.

**Comment by rydyclab** [comment]
> Вы знаете, можно ли использовать интерфейс I2C на этом блоке питания? Спасибо.

Works i2c

**Comment by flywire** [comment]
> Works i2c

Can you link instructions?

**Comment by rydyclab** [comment]
> > Работает по протоколу I2C
> 
> Можете дать ссылку на инструкцию?

https://github.com/slundell/dps_charger/
