### ISSUE TITLE
 hstns-pl30 - Anyone up for giving me some guidance?

### ISSUE THREAD

**Issue by mike-newman** [darwinbeing/HPServerPSUHack#6]
Hello, 

Been trying to understand the documentation here and procedures to modify my hstns-pl30 for coding my BMW E66. The goal is to mod the  hstns-pl30 for 14.7 volts and max avaialble AMPs (80AMP?) 

So far I have been aboe to add the resitor to power on the unit, I have 12.3 volts when powered on. Where I need assistance is the correct reistors and placement needed to bring the voltage up above 14v and OVP so the unit doenst shut off. I cant tell if I need to both solder the resitors and or program the unit. 

I see the images provided in the repo but cant really tell exactly where to solder. 

Please any assistance is appreciated. 

Mike

**Comment by darwinbeing** [comment]
$`R_1{\approx}1.1Kohms`$
$`R_2{\approx}4.12Kohms`$

![PL30_MOD](https://github.com/darwinbeing/HPServerPSUHack/assets/366633/eac129ed-25fc-4475-b1c2-1f5b2a327c89)
