### ISSUE TITLE
could you add a PL41 these r very cheap now but it is unknown how to adjust voltage it does not have any pots just op amps

### ISSUE THREAD

**Issue by Crunch69** [darwinbeing/HPServerPSUHack#8]
could you add a PL41 these r very cheap 800W 2 for $23 shipped now but it is unknown how to adjust voltage it does not have any pots just op amps.  in parallel you get a 24v 1600W supply.  it would be fantastic if we could get 26-28v out of them

**Comment by darwinbeing** [comment]
I don't have access to that power supply. Could you share a few clear close-up photos of it?
